### ISSUE TITLE
why is there a need for the id in the table displayed to the user?

### ISSUE THREAD

**Issue by shiryz** [FACN1/week6-hibas-angels#26]
https://github.com/FACN1/week6-hibas-angels/blob/master/public/index.js#L34

I don't see the need of showing the id of the book to the user, if you were thinking of the book's number (as in a real library) change the column's name.

**Comment by shiryz** [comment]
Only on the front end , you the id in the database as a primary key.

**Comment by jwld** [comment]
This was mainly us just playing around to see if things worked. But yea I'll take it out!
